services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - keycloak
  
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile-keycloak-with-opentelemetry
    ports:
      - 9464:9464
    environment:
      JAVA_OPTS_APPEND: "-javaagent:/tmp/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: keycloak
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4318
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_METRICS_ENABLED: "false"
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    depends_on:
      - otel
    command:
      - start-dev
      # - '--log-console-output=json'
      - '--log=console'
      - '--log-level=INFO'

  otel:
    container_name: otel
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel/otel-config.yaml:/etc/otel-config.yaml
    command:
      '--config=/etc/otel-config.yaml'
    environment:
      LOGSPOUT: ignore
    depends_on:
      - jaeger
      - prometheus
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - LOGSPOUT=ignore
      # - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./esconfig:/usr/share/elasticsearch/config

  elastic-apm:
    image: docker.elastic.co/apm/apm-server:8.14.1
    container_name: elastic-apm
    ports:
      - 8200:8200
    volumes:
      - "${PWD}/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      LOGSPOUT: ignore      
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 181a0b1964f9968093bd05e26c7a9b1c
      XPACK_REPORTING_ENCRYPTIONKEY: 618ad181c0786f4f3be6299fbf661de3
      XPACK_SECURITY_ENCRYPTIONKEY: a017e442013e766c008879dfcf48a78f
    depends_on:
      - elasticsearch
    volumes:
      - ./kidata:/usr/share/kibana/data
      - ./kiconfig:/usr/share/kibana/config
      
volumes:
  esdata:
  esconfig:
  kiconfig:
  kidata:
