services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - keycloak
  
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile-keycloak-with-opentelemetry
    ports:
      - 9464:9464
    environment:
      JAVA_OPTS_APPEND: "-javaagent:/tmp/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: keycloak
      OTEL_TRACES_EXPORTER: otlp
      # OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4317
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_METRICS_ENABLED: "false"
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    depends_on:
      - otel
    command:
      - start-dev
      - '--log-console-output=json'
      - '--log=console'
      - '--log-level=DEBUG'

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686 # Jaeger UI
      - 4317:55680  # GRPC OTLP
      - 13133:13133 # Healthcheck
    environment:
      LOGSPOUT: ignore

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/dashboards:/provisioning/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    environment:
      LOGSPOUT: ignore
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_HOME_PAGE: /d/Xbo7ftQnz/keycloak?orgId=1
    depends_on:
      - jaeger
      # - prometheus

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   ports:
  #     - 9090:9090
  #   environment:
  #     LOGSPOUT: ignore
  #   command: 
  #     - "--web.enable-remote-write-receiver"
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--web.console.libraries=/usr/share/prometheus/console_libraries"
  #     - "--web.console.templates=/usr/share/prometheus/consoles"

  otel:
    container_name: otel
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel/otel-config.yaml:/etc/otel-config.yaml
    command:
      '--config=/etc/otel-config.yaml'
    environment:
      LOGSPOUT: ignore
    depends_on:
      - jaeger
      # - prometheus
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch
    environment:
      - LOGSPOUT=ignore
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cap_add:
      - IPC_LOCK

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      LOGSPOUT: ignore      
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 181a0b1964f9968093bd05e26c7a9b1c
      XPACK_REPORTING_ENCRYPTIONKEY: 618ad181c0786f4f3be6299fbf661de3
      XPACK_SECURITY_ENCRYPTIONKEY: a017e442013e766c008879dfcf48a78f
    depends_on:
      - elasticsearch
      
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.3.3
  #   container_name: logstash
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     LOGSPOUT: ignore
  #   depends_on:
  #     - elasticsearch
      
  # logspout:
  #   image: gliderlabs/logspout:v3
  #   container_name: logspout
  #   command: 'udp://logstash:5044,syslog+udp://criblworker:9514?filter.name=nginx'
  #   environment:
  #     LOGSPOUT: ignore
  #   volumes:
  #     - '/var/run/docker.sock:/tmp/docker.sock'
  #   depends_on:
  #     - logstash

  # # Cribl
  # criblmaster:
  #   container_name: criblmaster
  #   image: cribl/cribl:latest
  #   environment:
  #     - LOGSPOUT=ignore
  #     - CRIBL_DIST_MODE=master
  #     - CRIBL_DIST_MASTER_URL=tcp://criblmaster@0.0.0.0:4200
  #     - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
  #     - CRIBL_BEFORE_START_CMD_1=/tmp/fix-git-dir.sh
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ./cribl-config-master:/opt/cribl/config-volume
  #     - ./cribl-scripts/fix-git-dir.sh:/tmp/fix-git-dir.sh
  # criblworker:
  #   container_name: criblworker
  #   image: cribl/cribl:latest
  #   depends_on:
  #     - criblmaster
  #   environment:
  #     - LOGSPOUT=ignore
  #     - CRIBL_DIST_MODE=worker
  #     - CRIBL_DIST_MASTER_URL=tcp://criblmaster@criblmaster:4200
  #     - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
  #     - CRIBL_BEFORE_START_CMD_1=/tmp/fix-git-dir.sh
  #   volumes:
  #     - ./cribl-config-worker:/opt/cribl/config-volume
  #     - ./cribl-scripts/fix-git-dir.sh:/tmp/fix-git-dir.sh

