extensions:
  # standard healthcheck
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  # OTLP receiver
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/otlp-traces:
    send_batch_size: 8192
    timeout: 1s
    send_batch_max_size: 0

exporters:

  otlphttp/elastic:
    endpoint: "http://elastic-apm:8200"

  logging:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/otlp-traces]
      exporters: [otlphttp/elastic]

